# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
fpath=(~/.zsh/completions $fpath)
autoload -Uz compinit
compinit
# End of lines added by compinstall



# Compinstall save file
zstyle :compinstall filename "$HOME/.zshrc"

# Direnv setup
eval "$(direnv hook zsh)"
# Starship setup
eval "$(starship init zsh)"

# fnm setup
if [[ -z "$IN_NIX_SHELL" ]]; then
    eval "$(fnm env --use-on-cd --shell zsh)"
fi

# Enable LS_COLORS
eval "$(dircolors -b)"

# Enable colored completion lists
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"

# Word characters for word navigation
# WORDCHARS=${WORDCHARS//\/}
# Ctrl + Arrow word navigation
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word
bindkey '^W' backward-kill-word
bindkey '^[[3;5~' kill-word

# Overwrite default behaviour with alises
alias ls='ls --color=auto'

# History substring
autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey '^[[A' up-line-or-beginning-search
bindkey '^[[B' down-line-or-beginning-search

#
setopt AUTO_PARAM_SLASH

# Reset cursor to beam (bar) after every command
precmd() { printf '\e[5 q' }

export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/.cargo/bin:$PATH"
